// Catalog data. Album art is SVG-generated (vinyl sleeve placeholders with
// hand-tuned color palettes) so the store feels real without hotlinking anywhere.

const CATALOG = [
  {
    id: 'ice-001', cat: 'ICE 001',
    artist: 'Midori Takada',
    title: 'Through the Looking Glass',
    year: 1983, label: 'RCA / Invisible City',
    format: 'LP', pressing: 'Reissue · 180g',
    condition: 'M', conditionLabel: 'Mint',
    price: 42.00, stock: 4,
    genre: ['Ambient', 'Minimal', 'Fourth World'],
    country: 'JP',
    palette: ['#c89a3c', '#1a1410', '#f4ede3'],
    sleeve: 'grid',
    tracks: [
      { n: 'A1', title: 'Mr. Henri Rousseau\'s Dream', len: '10:35', wave: 'soft' },
      { n: 'A2', title: 'Crossing', len: '6:23', wave: 'mid' },
      { n: 'B1', title: 'Trompe-l\'œil', len: '5:47', wave: 'soft' },
      { n: 'B2', title: 'Catastrophe Σ', len: '14:15', wave: 'hard' },
    ],
    notes: 'Private-press minimalism from the Tokyo percussionist. One long meditation on water, bells and memory. A record that rewards slow listening.',
  },
  {
    id: 'ice-002', cat: 'ICE 002',
    artist: 'Alice Coltrane',
    title: 'Journey in Satchidananda',
    year: 1971, label: 'Impulse!',
    format: 'LP', pressing: 'Original · Stereo',
    condition: 'VG+', conditionLabel: 'Very Good Plus',
    price: 85.00, stock: 1,
    genre: ['Spiritual Jazz', 'Free Jazz'],
    country: 'US',
    palette: ['#8b3a1f', '#f4ede3', '#0a0908'],
    sleeve: 'arc',
    tracks: [
      { n: 'A1', title: 'Journey in Satchidananda', len: '6:35', wave: 'mid' },
      { n: 'A2', title: 'Shiva-Loka', len: '6:35', wave: 'soft' },
      { n: 'A3', title: 'Stopover Bombay', len: '2:50', wave: 'hard' },
      { n: 'B1', title: 'Something About John Coltrane', len: '11:00', wave: 'mid' },
      { n: 'B2', title: 'Isis and Osiris', len: '11:35', wave: 'soft' },
    ],
    notes: 'Light ring wear, sleeve edges creased. Vinyl near-perfect — plays clean through. Pharoah Sanders on soprano, Cecil McBee on bass. Essential.',
  },
  {
    id: 'ice-003', cat: 'ICE 003',
    artist: 'Haruomi Hosono',
    title: 'Paraiso',
    year: 1978, label: 'Alfa',
    format: 'LP', pressing: 'Japanese Press',
    condition: 'NM', conditionLabel: 'Near Mint',
    price: 58.00, stock: 2,
    genre: ['Exotica', 'City Pop', 'Tropical'],
    country: 'JP',
    palette: ['#2a5f6e', '#eed8a0', '#0f1a1f'],
    sleeve: 'sun',
    tracks: [
      { n: 'A1', title: 'Tokio Rush', len: '3:41', wave: 'mid' },
      { n: 'A2', title: 'Shimendoka', len: '3:23', wave: 'soft' },
      { n: 'A3', title: 'Japanese Rhumba', len: '2:30', wave: 'hard' },
      { n: 'B1', title: 'Fujiyama Mama', len: '3:02', wave: 'hard' },
      { n: 'B2', title: 'Asatoya Yunta', len: '3:58', wave: 'soft' },
      { n: 'B3', title: 'Paraiso', len: '4:12', wave: 'mid' },
    ],
    notes: 'Before YMO. A warm, strange postcard from a tropical Tokyo that never existed. Original obi not included.',
  },
  {
    id: 'ice-004', cat: 'ICE 004',
    artist: 'Don Cherry & Jon Appleton',
    title: 'Human Music',
    year: 1970, label: 'Flying Dutchman',
    format: 'LP', pressing: 'Original',
    condition: 'VG', conditionLabel: 'Very Good',
    price: 34.00, stock: 1,
    genre: ['Free Jazz', 'Electronic'],
    country: 'US',
    palette: ['#6b2a1f', '#d9c8a8', '#0a0908'],
    sleeve: 'wave',
    tracks: [
      { n: 'A', title: 'Human Music (Part One)', len: '21:00', wave: 'hard' },
      { n: 'B', title: 'Human Music (Part Two)', len: '19:00', wave: 'hard' },
    ],
    notes: 'Light surface noise between tracks. Don Cherry\'s pocket trumpet against Moog. Deep groove artifact.',
  },
  {
    id: 'ice-005', cat: 'ICE 005',
    artist: 'Joe Hisaishi',
    title: 'Curved Music',
    year: 1986, label: 'Tokuma',
    format: '2×LP', pressing: '2024 Reissue',
    condition: 'M', conditionLabel: 'Mint',
    price: 68.00, stock: 6,
    genre: ['Ambient', 'Minimal', 'Electronic'],
    country: 'JP',
    palette: ['#1a3a4a', '#c89a3c', '#f4ede3'],
    sleeve: 'concentric',
    tracks: [
      { n: 'A1', title: 'View of the Silence', len: '7:10', wave: 'soft' },
      { n: 'A2', title: 'Winter', len: '5:55', wave: 'mid' },
      { n: 'B1', title: 'Sinking Sun', len: '8:22', wave: 'soft' },
      { n: 'C1', title: 'Curved Music I', len: '9:40', wave: 'mid' },
      { n: 'D1', title: 'Curved Music II', len: '11:05', wave: 'soft' },
    ],
    notes: 'Gatefold sleeve with obi strip and insert. The composer before the studios. Pressed at Pallas.',
  },
  {
    id: 'ice-006', cat: 'ICE 006',
    artist: 'Pharoah Sanders',
    title: 'Karma',
    year: 1969, label: 'Impulse!',
    format: 'LP', pressing: 'Original · Gatefold',
    condition: 'VG+', conditionLabel: 'Very Good Plus',
    price: 72.00, stock: 1,
    genre: ['Spiritual Jazz'],
    country: 'US',
    palette: ['#c43d2a', '#0a0908', '#eed8a0'],
    sleeve: 'sun',
    tracks: [
      { n: 'A', title: 'The Creator Has a Master Plan', len: '32:45', wave: 'hard' },
      { n: 'B', title: 'Colors', len: '5:45', wave: 'soft' },
    ],
    notes: 'Leon Thomas yodeling over a thirty-two minute tide. Corner bump, otherwise clean.',
  },
  {
    id: 'ice-007', cat: 'ICE 007',
    artist: 'Shintaro Sakamoto',
    title: 'How To Live With A Phantom',
    year: 2011, label: 'Mesh-Key',
    format: 'LP', pressing: 'US Press',
    condition: 'NM', conditionLabel: 'Near Mint',
    price: 32.00, stock: 3,
    genre: ['Psych Pop', 'City Pop'],
    country: 'JP',
    palette: ['#d9c8a8', '#8b3a1f', '#1a1410'],
    sleeve: 'portrait',
    tracks: [
      { n: 'A1', title: 'In A Phantom Mood', len: '3:50', wave: 'mid' },
      { n: 'A2', title: 'Extremely Fine', len: '4:02', wave: 'mid' },
      { n: 'A3', title: 'Don\'t Know What\'s Normal', len: '3:21', wave: 'soft' },
      { n: 'B1', title: 'Something\'s Not Right', len: '3:48', wave: 'mid' },
      { n: 'B2', title: 'You Can Be A Robot, Too', len: '4:15', wave: 'hard' },
    ],
    notes: 'Ex-Yura Yura Teikoku. Loose, wry, unsentimental pop. Hype sticker intact.',
  },
  {
    id: 'ice-008', cat: 'ICE 008',
    artist: 'Suzanne Ciani',
    title: 'Seven Waves',
    year: 1982, label: 'Finnadar',
    format: 'LP', pressing: 'Original',
    condition: 'VG+', conditionLabel: 'Very Good Plus',
    price: 95.00, stock: 1,
    genre: ['New Age', 'Electronic', 'Ambient'],
    country: 'US',
    palette: ['#1a3a5a', '#a8c8d9', '#0a0908'],
    sleeve: 'wave',
    tracks: [
      { n: 'A1', title: 'The First Wave: Birth of Venus', len: '7:28', wave: 'soft' },
      { n: 'A2', title: 'The Second Wave: Sirens', len: '4:49', wave: 'mid' },
      { n: 'A3', title: 'The Third Wave: Love in the Waves', len: '5:42', wave: 'soft' },
      { n: 'B1', title: 'The Fourth Wave: Sea of Tranquility', len: '6:14', wave: 'soft' },
      { n: 'B2', title: 'The Fifth Wave: The Wanderer', len: '4:11', wave: 'mid' },
      { n: 'B3', title: 'The Seventh Wave: The Eighth Wave', len: '7:55', wave: 'soft' },
    ],
    notes: 'Buchla sorcery. Small seam split at the bottom. Plays perfectly.',
  },
  {
    id: 'ice-009', cat: 'ICE 009',
    artist: 'Mkwaju Ensemble',
    title: 'Ki-Motion',
    year: 1981, label: 'Better Days',
    format: 'LP', pressing: 'Japanese Press',
    condition: 'NM', conditionLabel: 'Near Mint',
    price: 64.00, stock: 2,
    genre: ['Minimal', 'Percussion', 'Fourth World'],
    country: 'JP',
    palette: ['#0a0908', '#c89a3c', '#8b3a1f'],
    sleeve: 'grid',
    tracks: [
      { n: 'A1', title: 'Lemore', len: '5:40', wave: 'hard' },
      { n: 'A2', title: 'Shak Shak', len: '4:15', wave: 'hard' },
      { n: 'A3', title: 'Ki-Motion', len: '7:02', wave: 'mid' },
      { n: 'B1', title: 'Pulse in the Mind', len: '8:20', wave: 'mid' },
      { n: 'B2', title: 'Wooden Bells', len: '6:50', wave: 'soft' },
    ],
    notes: 'Midori Takada\'s ensemble. Marimbas, logs, gongs. A piece of Japanese minimalism not often found outside of Tokyo shops.',
  },
  {
    id: 'ice-010', cat: 'ICE 010',
    artist: 'Arthur Russell',
    title: 'World of Echo',
    year: 1986, label: 'Upside',
    format: 'LP', pressing: 'Audika Reissue',
    condition: 'M', conditionLabel: 'Mint',
    price: 48.00, stock: 5,
    genre: ['Avant-Garde', 'Ambient'],
    country: 'US',
    palette: ['#3a4a5a', '#eed8a0', '#0a0908'],
    sleeve: 'portrait',
    tracks: [
      { n: 'A1', title: 'Tone Bone Kone', len: '3:05', wave: 'soft' },
      { n: 'A2', title: 'Tower of Meaning / Rabbit\'s Ear / Home Away from Home', len: '4:40', wave: 'soft' },
      { n: 'A3', title: 'Answers Me', len: '3:50', wave: 'mid' },
      { n: 'B1', title: 'Being It', len: '3:42', wave: 'soft' },
      { n: 'B2', title: 'Place I Know / Kid Like You', len: '5:10', wave: 'mid' },
    ],
    notes: 'Cello, voice, and delay pedals in a downtown loft. Audika reissue with the original 1986 mastering. Sounds like weather.',
  },
  {
    id: 'ice-011', cat: 'ICE 011',
    artist: 'Yasuaki Shimizu',
    title: 'Kakashi',
    year: 1982, label: 'Better Days',
    format: 'LP', pressing: '2017 Reissue',
    condition: 'NM', conditionLabel: 'Near Mint',
    price: 38.00, stock: 3,
    genre: ['Experimental', 'Jazz', 'Electronic'],
    country: 'JP',
    palette: ['#6e8b3a', '#f4ede3', '#1a1410'],
    sleeve: 'concentric',
    tracks: [
      { n: 'A1', title: 'Utsukushiki Tennen', len: '4:20', wave: 'mid' },
      { n: 'A2', title: 'Suiren', len: '5:15', wave: 'soft' },
      { n: 'A3', title: 'Kono Yo Ni Nai Mono', len: '4:50', wave: 'mid' },
      { n: 'B1', title: 'Kakashi', len: '7:30', wave: 'soft' },
      { n: 'B2', title: 'Umi No Ue Kara', len: '6:05', wave: 'mid' },
    ],
    notes: 'Saxophone, marimba, and a synthesized haze. Shimizu at his most pastoral.',
  },
  {
    id: 'ice-012', cat: 'ICE 012',
    artist: 'Steve Reich',
    title: 'Music for 18 Musicians',
    year: 1978, label: 'ECM',
    format: 'LP', pressing: 'Original · German',
    condition: 'VG+', conditionLabel: 'Very Good Plus',
    price: 54.00, stock: 2,
    genre: ['Minimal', 'Contemporary Classical'],
    country: 'DE',
    palette: ['#f4ede3', '#1a1410', '#c89a3c'],
    sleeve: 'arc',
    tracks: [
      { n: 'A', title: 'Pulses / Section I / Section II / Section IIIA', len: '28:00', wave: 'mid' },
      { n: 'B', title: 'Section IIIB / Section IV / Section V...', len: '28:00', wave: 'mid' },
    ],
    notes: 'The ECM pressing. Spine clean, no splits. A cornerstone.',
  },
];

const GENRES = ['All', 'Ambient', 'Minimal', 'Spiritual Jazz', 'City Pop', 'Electronic', 'Experimental', 'Fourth World', 'New Age'];
const FORMATS = ['All', 'LP', '2×LP', '7"', '12"'];
const CONDITIONS = ['All', 'M', 'NM', 'VG+', 'VG'];
const SORTS = ['Newest', 'Price ↑', 'Price ↓', 'Artist A→Z', 'Year ↑'];

window.CATALOG = CATALOG;
window.GENRES = GENRES;
window.FORMATS = FORMATS;
window.CONDITIONS = CONDITIONS;
window.SORTS = SORTS;
